%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
padre(rodrigo,erwis).
padre(rodrigo,citlali).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
padre(benito,beny).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
padre(apolinar,tito).
padre(apolinar,javier).
padre(apolinar,fabiola).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
padre(fidel,rodrigo).
padre(fidel,rusbel).
padre(fidel,benito).
padre(fidel,gerardo).
padre(fidel,azalea).
padre(fidel,lucina).
padre(fidel,bernardo).
padre(fidel,romeo).
padre(fidel,fidel).
padre(fidel,fernando).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
madre(esther,rodrigo).
madre(esther,rusbel).
madre(esther,benito).
madre(esther,gerardo).
madre(esther,azalea).
madre(esther,lucina).
madre(esther,bernardo).
madre(esther,romeo).
madre(esther,fidel).
madre(esther,fernando).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
madre(azalea,tito).
madre(azalea,javier).
madre(azalea,fabiola).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
madre(adriana,beny).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
madre(maria,erwis).
madre(maria,citlali).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
abuelo(A,B):-padre(A,C),padre(C,B).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
abuela(A,B):-madre(A,C),madre(C,B).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
hermano(A,B):-padre(P,A),padre(P,B),A\==B.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
tio(A,B):-padre(A,B).
%abuelo(A,B):-padre(C,B).

